### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by kpwilliams** [psanse/clique_enum#1]
Any instructions on installation?
I'm not very familiar with cmake. 
Tried:
$ cmake CMakeLists.txt
and eventually got this error: “CMake Error at copt/CMakeLists.txt:34 (target_link_libraries):  Cannot specify link libraries for target ‘published_alg’ which is not built by this project.”
How important is published_alg?

**Comment by psanse** [comment]
Hi,
Sorry for the late reply, The repo is not being supported any more.  Nevertheless I will look into it asap.
Pablo

**Comment by psanse** [comment]
Hi again,
I looked at the code and fixed some bugs in the Linux Version. Should be working now. Creates the binary mentioned in the instructions. If you have any problem please let me know
Pablo

**Comment by kpwilliams** [comment]
Thanks. Just to be clear here are the steps that worked:
$ cd clique_enum-master
$ cmake .
$ make
$ bin/greedy_bb
